### ISSUE TITLE
Update python related tutorials, adapters etc. to new Interface

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#432]
This includes:

- [x] fenics-adapter
- [x] nutils tutorials https://github.com/precice/tutorials/pull/58
- [x] solverdummies
- [x] python tube https://github.com/precice/elastictube1d/issues/18
- [x] system tests https://github.com/precice/systemtests/pull/123

don't do this before the new interface (see #379) is released, because otherwise users with preCICE < 1.6.0 cannot use the tutorials anymore, before 1.6.0 has been released.

## Todo

- [x] remove duplicate `python_future/solverdummy` and `python_future/test/solverdummy`
