### ISSUE TITLE
Extend data mapping to volume coupling

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#468]
# Volume Coupling

## Current Situation

preCICE was designed primarily with surface coupling in mind.
This means that the nearest-projection mapping make assumptions which are wrong for volume coupling. Using 2D Meshes, the mapping will only map to edges, not triangles.
The current workaround is to use a nearest-neighbor mapping with vertex information only.
Furthermore, preCICE does not support 3 dimensional primitives such as tetrahedra or hexahedra.

## The Goal

preCICE and its mapping algorithms should handle volume coupling in all cases correctly.
It should also be possible to at least tetrahedra via the interface.

## Work Packages

* [ ] Extend `MappingRequirement` and fix the requirement for the various mappings.
* [x] Extend the configuration adding a switch between surface and volume coupling.
* [x] Extend SolverInterface to support adding Tetrahedra (`setMeshTertrahedron()`)
* [x] Extend exporters to support writing Tetrahedra (e.g. VTK)
* [x] Add support to interpolating in Tetrahedra as well as generating interpolation elements
* [x] Add necessary adapters to allow usage and indexing of tetrahedra in `Boost.Geometry`.

**Comment by MakisH** [comment]
Just to be clear, preCICE currently is successfully being used for volume coupling (see, e.g. [this talk](https://www.youtube.com/watch?v=TrZD9SnG2Ts)), but not all the features are currently supported / make sense (mainly: nearest-projection mapping).

**Comment by uekerman** [comment]
I adjusted the title because this issue is mainly a collection for what is needed to extend the data mapping to volume coupling.
There are other themes as well, e.g. how to do realize and optimize for in-memory communication, but that's better tackled in a separate issue later.

**Comment by fsimonis** [comment]
As soon as we document that the user should prefer to triangulate quads and tetrahedrize hexahedra, we can close this issue.

[Defining mesh connectivity](https://precice.org/couple-your-code-defining-mesh-connectivity)
