### ISSUE TITLE
Discuss and improve error messages

### ISSUE THREAD

**Issue by uekerman** [precice/precice#698]
I collected all error messages in preCICE (`PRECICE_CHECK`, `PRECICE_ERROR`, `runtime_error`). Not yet sure what to do with them exactly. Let's discuss here. I think we all agree that we need to improve things here.

The best way is probably to directly improve the error messages. Add more information, more context, next steps, etc. For some errors, we probably also need further information in the wiki.

Quite some errors need to be assertions instead. 

Let's also agree on a style and wording. 
* I suggest to define that error messages always have to end with a period ".". "!" is forbidden :smirk: 
* Let's not say "solver" or "accessor", but always "participant" or "this participant".
* Use data names instead of IDs etc.
* More things?
* Format:
  * 1 line (no `\n`)
  * "What you did wrong. Hint or solution to fix it."

Example:  
   ```cpp
  This participant does not provide Mesh "NodeCenters", but attempted to modify it. Please extend the use-mesh tag as follows <use-mesh name="NodeCenters" provide="yes" >.
```

Fur sure this needs to be a common effort (coding days?). We could use the list to check updates and assign developers to blocks.

_Note: Checkboxes in `<detail>` are broken._

# 1. Wrong configuration

## 1.1 Data and mesh config #728 @MakisH 

- [x] Data "MyData" cannot be created twice for mesh "MyMesh"!
- [x] Data "MyData" uses non-unique name!
- [x] Data "MyData" is not available in data configuration!
- [x] Unknown data type!
- [x] Data with name "MyData" is not available during configuration of mesh "MyMesh"

### 1.2.1 use-mesh, read-data, write-data

- [x] Participant "MyParticipant" cannot provide and receive mesh "MyMesh"!
- [x] Participant "MyParticipant" must either provide or receive the mesh "MyMesh"!
- [x] Participant "MyParticipant" cannot receive and provide mesh "MyMesh" at the same time!
- [x] Mesh "MyMesh" cannot be used twice by participant "MyParticipant"!
- [x] Participant "MyParticipant" has to use "MyMesh" in order to write data to it!
- [x] Participant "MyParticipant" has to use mesh "MyMesh" when writing data to it!
- [x] Participant "MyParticipant" has to use "MyMesh" in order to read data from it!
- [x] Data action of participant "MyParticipant" uses mesh which is not used by the participant
- [x] Participant "MyParticipant" defines watchpoint "MyWatchpoint" for mesh "MyMesh" which is not used by him!
- [x] The participant "MyParticipant" needs to use the mesh "MyMesh" if he wants to use it in the coupling scheme.
- [x] Participant "MyParticipant" can read/write data "MyData" only once!
- [x] Participant "MyParticipant" uses mesh "MyMesh" which is not received (no "from"), but has a geometric-filter and/or a safety factor defined. This is not valid."
- [x] Participant "MyParticipant" uses mesh "MyMesh" which is not defined
- [x] Safety Factor must be positive or 0

### 1.2.2 mapping

- [x] Participant "MyParticipant" has mapping from mesh "MyMesh" which he does not use!
- [x] Participant "MyParticipant" has mapping to mesh "MyMesh" which he does not use!
- [x] The mesh "MyMesh" needs to use the data "MyData" to allow the write mapping
- [x] The mesh "MyMesh" needs to use the data "MyData" to allow the read mapping
- [x] A read mapping of participant "MyParticipant" needs to map TO a provided mesh. Mesh "MyMesh" is not provided.
- [x] A read mapping of participant "MyParticipant" needs to map FROM a received mesh. Mesh "MyMesh" is not received.
- [x] A write mapping of participant "MyParticipant" needs to map FROM a provided mesh. Mesh "MyMesh" is not provided.
- [x] A write mapping of participant "MyParticipant" needs to map TO a received mesh. Mesh "MyMesh" is not received.
- [x] The received mesh "MyMesh" needs a mapping, either from it, to it, or both. Maybe you don't want to receive this mesh at all?
- [x] There cannot be two mappings from mesh "MyMesh"
- [x] There cannot be two mappings to mesh "MyMesh"
- [x] Mesh "MyMesh" not defined at creation of mapping!
- [x] Unknown direction type "WrongOption"!
- [x] Unknown mapping constraint "WrongOption"!
- [x] Unknown mapping type!
- [x] Unknown timing value "WrongOption"

### 1.2.3 mapping:rbf

- [x] [DEPRECATED] Using RBF data mappings in parallel requires building with PETSc.
- [x] You cannot choose all axes to be dead for a RBF mapping
- [x] [DEPRECATED]  RBF mapping is not supported for a participant in master mode, use petrbf instead
- [x] Shape parameter for radial-basis-function inverse multiquadric has to be larger than zero!
- [x] Shape parameter for radial-basis-function gaussian has to be larger than zero!
- [x] Support radius for radial-basis-function gaussian has to be larger than zero!
- [x] Support radius for radial-basis-function compact thin-plate-splines c2 has to be larger than zero!
- [x] Support radius for radial-basis-function compact polynomial c0 has to be larger than zero!
- [x] Support radius for radial-basis-function compact polynomial c6 has to be larger than zero!

## 1.3 Actions #810 @KyleDavisSA 

- [x] Unknown action timing "WrongOption"!
- [x] No mesh ID found!
- [x] Creating python source values failed!
- [x] Creating python target values failed!
- [x] Creating python ID failed!
- [x] Creating python coords failed!
- [x] Creating python normal failed!
- [x] Data action uses mesh "MyMesh" which is not configured
- [x] Data action uses source data "MyData" which is not configured
- [x] Data action uses target data "MyData" which is not configured

## 1.4 Export

- [x] Unknown export type!

## 1.5 Communication @fsimonis 

- [x] The value given for the "port" attribute is not a 16-bit unsigned integer: 42
- [x] MPI communication direct (i.e. single) can be only used with more than one process in base communicator!
- [x] When building with \"mpi=off\", you need to specify an alternative "master" communication (e.g. sockets) for every parallel participant
- [x] Communication type "mpi" can only be used when preCICE is compiled with argument "mpi=on"
- [x] Communication type "mpi-singleports" can only be used when preCICE is compiled with argument "mpi=on"
- [x] No m2n communication configured between "MyParticipant" and "OtherParticipant"!
- [x] Multiple communication defined between participant "MyParticipant" and "OtherParticipant"

### 1.6.1 basics

- [x] [Unknown coupling scheme type!](https://github.com/precice/precice/blob/4c1fd364d1ea2b9d7780b9d0882bd713141828bb/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L385)
- [x] [No coupling scheme defined for participant "MyParticipant"!](https://github.com/precice/precice/blob/4c1fd364d1ea2b9d7780b9d0882bd713141828bb/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L138-L140)
- [x] Only one controller per MultiCoupling can be defined
- [x] One controller per MultiCoupling need to be defined
- [x] You cannot define an exchange from and to the same participant
- [x] [Only second participant can initialize data!](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/SerialCouplingScheme.cpp#L66) related #714, configuration or API usage?
- [x] [Only first participant can receive initial data!](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/SerialCouplingScheme.cpp#L75) related #714, configuration or API usage? 
- [x] Mesh "MyMesh" with data "MyData" not defined at definition of coupling scheme
- [x] Participant "MyParticipant" is not configured for coupling scheme

### 1.6.2 time

- [x] Unknown timestepping method "WrongOption"
- [x] [Maximum number of time windows has to be larger than zero!](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/BaseCouplingScheme.cpp#L41-L48). Use `PRECICE_ASSERT` in coupling scheme and perform a `PRECICE_CHECK` in configuration -> #712 
- [x] [Time window size has to be larger than zero!](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/BaseCouplingScheme.cpp#L41-L48). Use `PRECICE_ASSERT` in coupling scheme and perform a `PRECICE_CHECK` in configuration -> #712
- [x] Valid digits of time window size has to be between 1 and 16!
- [x] [Maximum time has to be larger than zero!](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/BaseCouplingScheme.cpp#L41-L48). Use `PRECICE_ASSERT` in coupling scheme and perform a `PRECICE_CHECK` in configuration -> #712
- [x] [Maximum number of time windows has to be larger than zero!](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/BaseCouplingScheme.cpp#L41-L48). Use `PRECICE_ASSERT` in coupling scheme and perform a `PRECICE_CHECK` in configuration -> #712
- [x] Valid digits of timestep length has to be between 1 and 16!

### 1.6.3 implicit

- [x] You need to exchange every data that you use for convergence measures and/or the iteration acceleration
- [x] At least one convergence measure has to be defined for an implicit coupling scheme!
- [x] No send data configured! Use explicit scheme for one-way coupling. [here](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/ParallelCouplingScheme.cpp#L45) and [here](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/SerialCouplingScheme.cpp#L46). First #689 (:heavy_check_mark:) and merge https://github.com/precice/precice/compare/remove_check_configuration 
- [x] [For multi coupling, the number of coupling data vectors has to be at least 3, not: 2](https://github.com/precice/precice/blob/cea4546eb84cf8aec66307f24f8f456451839230/src/cplscheme/MultiCouplingScheme.cpp#L50-L52) related #714  ... first merge https://github.com/precice/precice/compare/remove_check_configuration 
- [x] Relative convergence limit has to be in ]0;1] !
- [x] Absolute convergence limit has to be greater than zero!
- [x] First participant and second participant must have different names! Called from BaseCoupling.
- [x] Timestep length value has to be given when the fixed timestep length method is chosen for an implicit coupling scheme! -> Currently, unreachable. We cannot differentiate between default `value=-1` and provided `value=-1`. The first should raise this error, the latter should raise `Time window size has to be larger than zero!`
- [x] Maximal iteration limit has to be larger than zero!
- [x] Extrapolation order has to be 0, 1, or 2!

## 1.7 Acceleration config #809 @KyleDavisSA 

- [x] Acceleration of type "WrongOption" is unknown!
- [x] In case of serial coupling, acceleration can be defined for data of second participant only!
- [x] Initial relaxation factor for QN acceleration has to be larger than zero and smaller or equal than one!
- [x] Maximal iterations used for QN acceleration has to be larger than zero!
- [x] Number of old timesteps to be reused for QN acceleration has to be >= 0!
- [x] Relaxation factor for constant relaxation acceleration has to be larger than zero and smaller or equal than one!
- [x] Initial relaxation factor for aitken acceleration has to be larger than zero and smaller or equal than one!
- [x] Maximal iterations used for MM acceleration has to be larger than zero!
- [x] Maximal iterations used for coarse model optimization for MM acceleration has to be larger than zero!
- [x] Number of old timesteps to be reused for MM acceleration has to be >= 0!
- [x] Acceleration IQN-IMVJ only works if preCICE is compiled with MPI
- [x] Design specification for constant relaxation is not supported yet.
- [x] IMVJ can not be in restart mode while parameter always-build-jacobian is set true.
- [x] design specification for Aitken relaxation is not supported yet.
- [x] truncated IMVJ no longer supported, needs to be parallelized and datastructures need to be changed to Eigen datastructures.
- [x] Data ID 42 is not contained in the exchange data for the fine model and no coarse model optimization method is defined.
- [x] Data with name "MyData" associated to mesh "MyMesh" not found on configuration of acceleration

## 1.8 Further config @uekerman 

- [x] Two-level initialization does not yet support multiple receivers of a provided mesh.
- [x] A gather-scatter m2n communication cannot use two-level initialization.
- [x] To use two-level initialization, both participants need to run in parallel.
- [x] You cannot use a master with a serial participant.
- [x] At least two participants need to be defined!

## 1.9 Technical config @fsimonis 

- [x] Received callback from tag "TagName"
- [x] Vector attribute "AttributeName" of tag "TagName" has less dimensions than required (2 instead of 3)!
- [x] String to Double error
- [x] String to Int error
- [x] Tag <TagName> is unknown
- [x] Tag <TagName> is already used
- [x] Attribute "AttributeName" is defined multiple times
- [x] Attribute "AttributeName" missing
- [x] Wrong attribute "AttributeName"
- [x] Tag <TagName> is missing
- [x] Tag <TagName:...> is missing

# 2 API used incorrectly

## 2.1 Interface creation @uekerman 

- [x] Accessor has to be named!
- [x] Unknown accessor name "MyParticipant"!
- [x] Accessing participant "MyParticipant" is not defined in configuration!
- [x] Accessor process index has to be >= 0!
- [x] Accessor process size has to be >= 0!
- [x] Accessor process index has to be smaller than accessor process size (given as 42)!
- [x] The passed solverProcessIndex (42) does not match the rank of the passed MPI communicator (43)
- [x] The passed solverProcessSize (42) does not match the size of the passed MPI communicator (43)

## 2.2 Steering @BenjaminRueth 

- [x] initialize() may only be called once.
- [x] initialize() has to be called before initializeData()
- [x] initialize() has to be called before advance()
- [x] advance() cannot be called when isCouplingOngoing() returns false
- [x] initialize() has to be called before finalize()
- [x] initializeData() can be called after initialize() only!
- [x] initializeData() needs to be called before advance if data has to be initialized!
- [x] Called finalize() before initialize()!
- [x] InitialData has to be written to preCICE before calling initializeData()

## 2.3 Mesh definition @fsimonis 

- [x] This participant is required to use Mesh "MyMesh"!
- [x] This participant is required to provide Mesh "MyMesh"!
- [x] This participant attempted to modify the locked Mesh "MyMesh"!
- [x] Mesh with name "MyMesh" is not defined!
- [x] Given VertexID is invalid!
- [x] Given EdgeID is invalid!
- [x] Given EdgeIDs must be unique!
- [x] Given VertexIDs must be unique!
- [x] The coordinates of the vertices must be unique!
- [x] Edges are not connected!
- [x] The provided mesh "MyMesh" is invalid (possibly empty).
- [x] This participant seems to have no mesh partitions for mesh "MyMesh" at the coupling interface.
- [x] The re-partitioning completely filtered out the mesh "MyMesh" received on this rank at the coupling interface. Most probably, the coupling interfaces of your coupled participants do not match geometry-wise. Please check your geometry setup again. Small overlaps or gaps are no problem. If your geometry setup is correct and if you have very different mesh resolutions on both sides, increasing the safety-factor of the decomposition strategy might be necessary.

## 2.4 Data access #812  @KyleDavisSA 
- [x] Data with name "MyData" is not defined on mesh with ID 42.
- [x] You cannot call writeBlockVectorData on the scalar data type "MyData"
- [x] Value index out of range
- [x] You cannot call writeVectorData on the scalar data type "MyData"
- [x] You cannot call writeBlockScalarData on the vector data type "MyData"
- [x] You cannot call writeScalarData on the vector data type "MyData"
- [x] You cannot call readBlockVectorData on the scalar data type "MyData"
- [x] You cannot call readVectorData on the scalar data type "MyData"
- [x] You cannot call readBlockScalarData on the vector data type "MyData"
- [x] You cannot call readScalarData on the vector data type "MyData"
- [x] Invalid value index ( 42 )when writing scalar data!
- [x] Invalid value index ( 42 )when reading vector data!

## 2.5 Further API #730 @uekerman 

- [x] Unfulfilled required actions: "ActionName"!
- [x] A mesh with only initial mappings must not be reseted
- [x] A mesh with no mappings must not be reseted
- [x] Ambiguous timestep length when calling request advance from several processes!
- [x] The computed timestep length of 0.3 exceeds the maximum timestep limit of 0.2 for this time step!
- [x] From mesh "MyMesh", there is no mapping defined

# 3 Erroneous system #740 

## 3.1 Communication

- [x] Already connected!
- [x] Requester communicator size has to be > 0!
- [x] Requester communicator sizes are inconsistent!
- [x] Duplicate request to connect by same rank 42!
- [x] Network "lo0" not found for socket connection!
- [x] Network interface "MyNetworkInterface" has too long name
- [x] Could not obtain network IP from network "MyNetworkInterface"
- [x] The SocketSendQueue is not empty upon destruction.
- [x] Accepting connection at "MyAddress" failed: ...
- [x] Requesting connection to "MyAddress" failed: ...
- [x] Send failed: ...
- [x] Receive failed: ...

## 3.2 File system

- [x] Could not open master file "MyFile" for VTKXML export!
- [x] Could not open slave file "MyFile" for VTKXML export!
- [x] Could not open file "MyFile" for VTK export!
- [x] Could not open file "MyFile" for txt writing!
- [x] Could not open file "MyFile" for txt reading!
- [x] File open error: "Path/To/MyFile"

## 3.3 Python Actions

- [x] Error occurred during call of function performAction() python module "ModuleName"!
- [x] Error occurred during call of function vertexCallback() python module "ModuleName"!
- [x] Error occurred during call of function postAction() in python module "ModuleName"!
- [x] Could not load python module "ModuleName" at path "Path/To/Module"!

# 4 Numerical problems #725 @uekerman 

- [x] RBF interpolation matrix is not invertible! "
- [x] RBF Polynomial linear system has not converged. Try to fix axis-aligned mapping setups by marking perpendicular axes as dead.
- [x] RBF linear system has not converged. Try to fix axis-aligned mapping setups by marking perpendicular axes as dead.
- [x] Polynomial QR linear system has not converged. Try to fix axis-aligned mapping setups by marking perpendicular axis as dead.
- [x] RBF linear system has not converged. Try to fix axis-aligned mapping setups by marking perpendicular axis as dead.
- [x] The coupling iteration in time step 42 failed to converge and NaN values occurred throughout the coupling process.
- [x] The coupling iteration in time step 42 failed to converge and NaN values occured throughout the coupling process. This is most likely due to the fact that the coarse model failed to converge within the given maximum number of allowed iterations: 10

# 5 Origin or reason unknown #727 @fsimonis #820 @MakisH 

- [x] Not implemented for dimension != 2!
- [x] Data with ID 42 is not contained in data given at initialization!
- [x] There is no Mesh with ID:42
- [x] There is no Data with ID 42
- [x] Data is not marked as read! 42
- [x] Data is not marked as write! 42
- [x] Data is not used by this participant! 42
- [x] Position 1=42 unknown!
- [x] Environment variable PRECICE_ROOT has not been set. Please set it to the precice directory.
- [x] Data with ID 42 not found in mesh "MyMesh"!
- [x] Called extrapolation with order != 1,2!
- [x] Participant "MyParticipant" does not use mesh "MyMesh"!
- [x] Name of local participant "MyParticipant" does not match any participant specified for the coupling scheme!
- [x] Data "MyData" used by mesh "MyMesh" is not configured!
- [x] Data "MyData" of mesh "MyMesh" cannot be added twice for sending!
- [x] Data "MyData" of mesh "MyMesh" cannot be added twice for receiving!

**Comment by MakisH** [comment]
As already discussed, it would be nice if ?every? error message suggested possible next steps, in the same style as Git error messages.

**Comment by BenjaminRueth** [comment]
Some error messages are improved in https://github.com/precice/precice/pull/721

**Comment by BenjaminRueth** [comment]
Let's organize how we are distributing the subtasks of this issue [here](https://github.com/precice/precice/projects/5)

**Comment by BenjaminRueth** [comment]
I would like to take over 1.6 Cplscheme config

**Comment by MakisH** [comment]
I would start with `1.1 Data and mesh config` and `1.2 Participant Config`.

**Comment by uekerman** [comment]
I can do 4 Numerical Problems

**Comment by BenjaminRueth** [comment]
`2.2 Steering` is also something I can take care of. Related #714.

**Comment by KyleDavisSA** [comment]
I can do `1.7 Acceleration Config`

**Comment by fsimonis** [comment]
:hand: I'll do the `5 Origin or reason unknown`

**Comment by MakisH** [comment]
Let's also use a consistent branch naming, e.g. `errors-1.2`.

**Comment by BenjaminRueth** [comment]
We now have check-boxes in the overview list (above) and I have put your names next to the sections that you took over responsibility for. 

Some rules to be able to keep track of the process:

* If you take over more sections, please don't forget to add your name above. 
* If an error messages is successfully "improved", please tick the check-box.

**Comment by uekerman** [comment]
I do 2.5 next

**Comment by KyleDavisSA** [comment]
I will do 1.3 next

**Comment by BenjaminRueth** [comment]
All error messages are now in good shape and PRs are merged. Therefore, we can close this overview issues 🎉
